version: '2'
services:
  database:
    container_name: magic_inventory
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./magic/magic_inventory/pgdata:/pgdata
    env_file:
      - ./magic/magic.env
  webserver:
    container_name: magic
    build: ./magic/api
    ports:
      - "9090:9090"
    env_file:
      - ./magic/magic.env
    depends_on:
      - database
