version: '3.7'
services:
  database:
    container_name: magic_inventory
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/var/lib/postgresql/data
  webserver:
    container_name: magic
    build: ./magic
    ports:
      - "9090:9090"
    depends_on:
      - database
    links:
      - database
