version: '3'
services:
  magic_inventory:
    container_name: magicinventory
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./magic/magicinventory/pgdata:/pgdata
    env_file:
      - ./magic/magic.env
    environment:
      - PGDATA=/var/lib/postgresql/data
  magic:
    container_name: magic
    build: ./magic
    ports:
      - "9090:9090"
    env_file:
      - ./magic/magic.env
    depends_on:
      - magic_inventory
    links:
      - magic_inventory
    volumes:
      - ./magic/magic.env:/etc/sysconfig/magic