swagger: "2.0"
info:
  description: "This is the `magic` server. Documented with [Swagger](http://swagger.io)."
  version: "1.0.0"
  title: "Magic Service"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:9090"
basePath: "/"
tags:
  - name: "wizards"
    description: "Everything about Wizards"
schemes:
  - "http"
paths:
  /wizards:
    get:
      tags:
        - "wizards"
      summary: "Find every Wizards from magicinventory DB"
      description: ""
      operationId: ""
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/MultipleWizardResponse'
  /wizards/{id}:
    get:
      tags:
        - "wizards"
      summary: "Find Wizard by ID"
      description: "Returns a single wizard"
      operationId: "GetWizardByID"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Wizard to return"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/SingleWizardResponse'
        404:
          description: "Wizard not found"
  /wizards/spawn:
    post:
      tags:
        - "wizards"
      summary: "Add Wizard to magicinventory DB"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Wizard object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Wizard"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: '#/definitions/SingleWizardResponse'
        422:
          description: "Cannot insert to database (might be duplicate)"
        405:
          description: "Method not Allowed: Invalid input"

definitions:
  Wizard:
    type: "object"
    required:
      - "id"
      - "first_name"
      - "last_name"
      - "age"
      - "category"
    properties:
      id:
        type: "string"
        example: "00000000-0000-0000-0000-000000000000"
      first_name:
        type: "string"
        example: "john"
      last_name:
        type: "string"
        example: "doe"
      age:
        type: "number"
        example: 0
      category:
        type: "string"
        description: "Wizard category in the magicinventory"
        enum:
          - "Families"
          - "Guests"
          - "Villains"
      arrested:
        type: "boolean"
        description: "Wizard jail status in the magicinventory"
        enum:
          - false
          - true
      dead:
        type: "boolean"
        description: "Wizard life status in the magicinventory"
        enum:
          - false
          - true
  SingleWizardResponse:
    $ref: '#/definitions/Wizard'
  MultipleWizardResponse:
    type: "array"
    items:
      $ref: '#/definitions/Wizard'

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"